### PR TITLE
Add some user settings

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,

This PR is very fresh and probably needs intense testing.
It requires the Imager module and to rerun setup_database.
See the commit comment for some more details.

To test, start by visiting the user's settings page.

Enjoy it !

Regards,
Patrick

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Very good! I uploaded my image and set web site, bio and etc.

I red also setup_database.

It looks like good.

You can merge this pull request.

**Comment by monnerat** [comment]
> Very good! I uploaded my image and set web site, bio and etc.

Thanks. I^m glad you like it !
I think we begin to have a pretty rich look :-))

I designed an rpm spec file to install GitPrep system-wide on a Fedora fdstribution. It works quite well and if you wish, I can include this spec file in your repo, maybe in a `packages` subdirectory.
The rpm package does not populate extlib, but has dependencies to other rpm packages. Some of them are not available in a bare Fedora, but I made them too (I plan to populate a copr (https://copr.fedorainfracloud.org/) project).
Tell me your feelings about it.

Will commit the current PR in a few minutes.

**Comment by monnerat** [comment]
BTW: what about changing the screenshot of the readme page and issue a new release ?

**Comment by monnerat** [comment]
> Will commit the current PR in a few minutes.

Done

**Comment by yuki-kimoto** [comment]
> I designed an rpm spec file to install GitPrep system-wide on a Fedora fdstribution. It works quite well and if you wish, I can include this spec file in your repo, maybe in a `packages` subdirectory. The rpm package does not populate extlib, but has dependencies to other rpm packages. Some of them are not available in a bare Fedora, but I made them too (I plan to populate a copr (https://copr.fedorainfracloud.org/) project). Tell me your feelings about it.

Please go ahead.

**Comment by yuki-kimoto** [comment]
> BTW: what about changing the screenshot of the readme page and issue a new release ?

I adjusted design details in master branch.

You can change the screenshot of the readme page and issue a new release?

**Comment by monnerat** [comment]
> I adjusted design details in master branch.

About d3b9a481b7f3193a05d9ed21f5d460f542ae0fd5: you have to keep `fill` if you want to have svg icons the same color as text.

**Comment by monnerat** [comment]
Also about 7940d72b0bc10490bae9189b2c32e4312b9c8224: `pre` should have monospace font because it is primarily intended for code display. This commit breaks ASCII art in commit messages and git directives on an empty repo look weird.

**Comment by monnerat** [comment]
There is now a repository for Fedora 41 users (x86_64 and aarch64): https://copr.fedorainfracloud.org/coprs/monnerat/gitprep/

Very, very simple :-)

**Comment by yuki-kimoto** [comment]
> There is now a repository for Fedora 41 users (x86_64 and aarch64): https://copr.fedorainfracloud.org/coprs/monnerat/gitprep/
> 
> Very, very simple :-)

Thanks.

**Comment by yuki-kimoto** [comment]
> > I adjusted design details in master branch.
> 
> About [d3b9a48](https://github.com/yuki-kimoto/gitprep/commit/d3b9a481b7f3193a05d9ed21f5d460f542ae0fd5): you have to keep `fill` if you want to have svg icons the same color as text.

Fixed.

90bed336628c56a913e6df8c0b0fb207e0e843b3

**Comment by yuki-kimoto** [comment]
> Also about [7940d72](https://github.com/yuki-kimoto/gitprep/commit/7940d72b0bc10490bae9189b2c32e4312b9c8224): `pre` should have monospace font because it is primarily intended for code display. This commit breaks ASCII art in commit messages and text/code file display, and git directives on an empty repo look weird.

Fixed.

ec040870371c0a20a50c4c8f721cd7b195d48ced

**Comment by monnerat** [comment]
Thanks for your design fixes :-)

**Pull request closed without merging**
