### PR TITLE
Better and easier setup + update

### PR DESCRIPTION
**Pull request by bilogic**
For #186 and #196

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Thank you very much. Almost OK.

Could you create `setup_script` and `setup_config` and call from `setup`?

`setup_script`

```
#!/bin/sh

CUR_DIR_ABS=$(cd $(dirname $0); pwd)

# Create gitprep-shell script

CURRENT_PERL=`which perl`
echo '#!/bin/sh' > script/gitprep-shell
echo -n "$CURRENT_PERL $CUR_DIR_ABS/script/gitprep-shell-raw" >> script/gitprep-shell
echo ' $*' >> script/gitprep-shell
chmod 755 script/gitprep-shell
```

`setup_config`

```
#!/bin/sh

# create config file from example if so that we can get going

if [ ! -e gitprep.conf ]; then
    cp gitprep.conf.example gitprep.conf
fi
```

`setup`

```
#!/bin/sh

./setup_module
./setup_script
./setup_config
./setup_database
```

**Comment by yuki-kimoto** [comment]
About `custom_template_folder`, I wait for a reply from @emil-perhinschi for a while.

**Comment by bilogic** [comment]
Done. I had to comment out `custom_template_folder`, otherwise can't install as not everyone has that hardcoded path.

**Comment by yuki-kimoto** [comment]
Thank you very much.

https://github.com/yuki-kimoto/gitprep/pull/197/commits/be70874ce789ce9bbffa265d981cb74b997326b9

I can merge this.

> Done. I had to comment out custom_template_folder, otherwise can't install as not everyone has that hardcoded path.

OK. I also think so.

I inform @emil-perhinschi this commit.

**Comment by bilogic** [comment]
arigato!

**Pull request merged**
