### PR TITLE
Show option to download repo as tar.gz

### PR DESCRIPTION
**Pull request by kaloyan13**
Code has support for downloading repo in tar.gz archive. I have replaced the butto "Download ZIP' with a HTML select.

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
@kaloyan13 

Thanks for contributing. I will check this and merge it.

**Comment by yuki-kimoto** [comment]
@kaloyan13

This is good feature. I want also good design.

Can you create Button and popup as GitHub? Popup contains links of "Donwload ZIP" and "Donwload tar.gz".

**Comment by kaloyan13** [comment]
No, I tried, but couldn't make the popup look nice.

**Comment by yuki-kimoto** [comment]
I don't have time to implement popup. I want to tar.gz button.

**Comment by yuki-kimoto** [comment]
Close this and add this to issue.

**Pull request closed without merging**
