### PR TITLE
Debugged compare behavior so that it correctly gets the base_project …

### PR DESCRIPTION
**Pull request by ThomasMcVay**
…and target_project variables. Also added compare across forks link to more closely match githubs appearance.

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
I will check this commit at first.

**Comment by yuki-kimoto** [comment]
@ThomasMcVay 

Your logic is wrong. For example.

Login your is "kimoto" and access the following URL.

    /kimoto/pull1/compare/b2?expand=1

Base and target branch should be

    base: master  ...   compare: b2

Your implementation is 

  base: master  ...   compare: master

This is wrong.

If you find bug, please tell me "login user" and "URL" and "base and target branch"

**Comment by ThomasMcVay** [comment]
I downloaded your new changes and created and set up a new test.

To test I created 2 users:
**TestUser**
**kimoto**

1. I log in as **TestUser**
2. I create a new repository **pull1** at **http://192.168.0.146:3000/TestUser/pull1.git**
3. On my local machine I run **git clone http://192.168.0.146:3000/TestUser/pull1.git**
4. I add a source file with some code.
5. I make the initial commit.
6. Then I run **git push origin master**
7. Then I logged out of **TestUser**

8. I log out of **TestUser**
9. I log in as **kimoto**.
10. I navigate to **http://192.168.0.146:3000/TestUser/pull1** 
11. I press the **Fork** button.
12. This creates a fork for **kimoto at http://192.168.0.146:3000/kimoto/pull1.git**
13. On my local machine I run git clone **http://192.168.0.146:3000/kimoto/pull1.git**
14. I create branch **b2**.
15. I add another source file to track.
16. I make another commit.
17. Then I run **git push origin b2**
  
18. Then I navigate to http://192.168.0.146:3000/kimoto/pull1/compare/b2?expand=1
  
     
This succeeds, and the compare page is correct. BUT if I click **compare across forks**, kimoto/pull1 is the only option I see under the fork buttons. So when I submit this request logged in as **kimoto** the request gets submitted TO **kimoto**. 

What I want to do is submit the pull request from **kimoto/pull1** to **TestUser/pull1**.
The buttons to do this should be:
**base fork: TestUser/pull1    base:master   head fork: kimoto/pull1    compare:b2**

But this is all I can do:
**base fork: kimoto/pull1    base:master   head fork: kimoto/pull1    compare:b2**


19. So I submit the pull request like that because it's all I can do
20. I log out of **kimoto**
21. I log in to **TestUser**
22. I navigate to **http://192.168.0.146:3000/TestUser/pull1/pulls** - my pull request shows up here (but it shouldn't because it was From: **kimoto** To: **kimoto**)
23. If I click the pull request it takes me to **http://192.168.0.146:3000/TestUser/pull1/pull/1** - Error
24. If I navigate to **http://192.168.0.146:3000/kimoto/pull1/pulls** -my pull request shows up
25. I can't click **Merge Pull Request** because I'm logged in as **TestUser**
26. I log out of **TestUser**
27. I log in to **kimoto**
28. I navigate to **http://192.168.0.146:3000/kimoto/pull1/pull/1** - this succeeds, no error
29. I click **Merge Pull Request** - this succeeds but only on the **kimoto** fork, not on **TestUser**

____________________________________________________________

A separate problem:
you asked me to go to 
**http://192.168.0.146:3000/kimoto/pull1/compare/b2?expand=1**
which works via the url

but if I go to:
**http://192.168.0.146:3000/kimoto/pull1/pulls**
and click **New pull request** it takes me to:
**http://192.168.0.146:3000/TestUser/pull1/compare/master...kimoto:master**

The buttons appear like this:
**base fork: TestUser/pull1    base:master   head fork: kimoto/pull1    compare:master**

but I get an error if I try to change to compare:b2 like this
**base fork: TestUser/pull1    base:master   head fork: kimoto/pull1    compare:master**


Maybe the **New pull request** button needs to be changed so that it takes you to
**http://192.168.0.146:3000/kimoto/pull1/compare/master?expand=1**
instead?

**Comment by yuki-kimoto** [comment]
thanks. 

> The buttons appear like this:
> base fork: TestUser/pull1 ... base:master ... head fork: kimoto/pull1 ... compare:master
> 
> but I get an error if I try to change to compare:b2 like this
> base fork: TestUser/pull1 ... base:master ... head fork: kimoto/pull1 ... compare:master

Is the last line is the following?

    base fork: TestUser/pull1 ... base:master ... head fork: kimoto/pull1 ... compare:b2

**Comment by ThomasMcVay** [comment]
Yes the last line should be that, sorry that was a typo

**Comment by yuki-kimoto** [comment]
I fixed pull reqeust error bug #111 

Let's try master, and tell me the result.

**Pull request closed without merging**
