### PR TITLE
displaying repos with default branch other than 'master' was not working

### PR DESCRIPTION
**Pull request by emil-perhinschi**
Hello, 

I could import repos with 'main' default branch but displaying them was not working. Also the repos were not created correctly when imported. Some code was already there to support custom default branches so I made it work correctly both when importing and when displaying.

This requires git 2.28 which was released 2 years ago ... I tested with git 2.30, not with versions older that 2.28 so this might break backwards compatibility, assuming backwards compatibility is important in this context.

An easy to use script to restart hypnotoad is included too.

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
OK.

> this might break backwards compatibility, assuming backwards compatibility is important in this context.

Let's try it and see how it goes.

**Comment by emil-perhinschi** [comment]
thanks

**Comment by emil-perhinschi** [comment]
Hello, 

Can you assign to me the issues you think need solving or create issues and assign them to me if you think something needs to be done or is worth doing ? 

I have some time on my hands and I'm not encumbered with work-for-hire contracts.

**Comment by yuki-kimoto** [comment]
> Can you assign to me the issues you think need solving or create issues and assign them to me if you think something needs to be done or is worth doing ?

OK.

**Comment by yuki-kimoto** [comment]
Do you have a bug you'd like to fix or a new feature you'd like to add?

**Comment by emil-perhinschi** [comment]
so far I fixed all the bugs I found :-) but I did not test it all, only imported all my personal repos and starting using my instance of gitprep as a remote 

this I see as a priority:
 - skins, that is being able to add alternative HTML/CSS designs and switch between them by changing gitprep.conf; path to extra templates configurable; this will allow keeping the templates separate, even in a separate repository, and not cause me to commit the changes I made to HTML/CSS 

relatively low hanging fruits: 
 - moving the data/rep and data/work folders outside the gitprep checkout folder (configurable in gitprep.conf): this will allow putting the repos on a partition that gets backed up, and the data/work somewhere else 
 - sorting/filtering/searching in the repo list
 - manually picking repos to showcase in the first page if hide_from_public is false: I think a boolean flag in the projects table would do, or more ambitiously let the admin and the users add tags to projects (separate table) and in gitprep.conf choose which tags should be shown
 - "repo language" tags, more than one unlike Github; chosen by users or admins, not autodetected, autodetection is not very reliable even on github
 - email notifications when exceptions happen, or when some other conditions are met (RAM usage, CPU usage)

 
 not so low: 
 - more automated testing ... this will require moving code out of templates
 - support for one or all of Postgresql/MariaDB/MySQL besides SQLite
 - adding a "status board" with configurable columns
 - searching in commits using the web gui

**Comment by yuki-kimoto** [comment]
OK.

Please post issues to add new features in the order of your priority.

I can assign you to the issues.

**Pull request merged**
