### PR TITLE
Icons: replace sprites by inline svg elements.

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,
This was a big job and I hope I did not introduce too many bugs! I'd appreciate a review and some testing.

The sprite png file is not used anymore by gitprep itself, but I kept it in case your DBViewer module is used. It should probably be deleted.

I wish you like the updated look!

Regards,
Patrick

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Thank you very much.

**Comment by yuki-kimoto** [comment]
Before.

image

After

image

**Comment by yuki-kimoto** [comment]
image

It looks work well.

I realized two things.

**Comment by monnerat** [comment]
> I realized two things.

- Header background: fixed.
- Tree icon vertical alignment: svg vertical alignment is a problem because, as images, they don't have a baseline like characters. So we are at mercy of the icon design. I determined the best compromise was vertical-align = sub for much of the cases, but for the tree icon, it seems to be vertical-align = baseline. I now introduced a class for that particular exception and it should look better.

BTW: can you provide a github issue template for private reports (not publicly visible) please. It's currently hard to tell you confidential stuff except by e-mail. Thanks.

**Comment by monnerat** [comment]
Thanks for merge :-)

**Comment by yuki-kimoto** [comment]
> BTW: can you provide a github issue template for private reports (not publicly visible) please. It's currently hard to tell you confidential stuff except by e-mail. Thanks.

Does this mean creating a private repository for GitPrep security issue?

Or is there a way to create a private issue?

**Comment by monnerat** [comment]
> Does this mean creating a private repository for GitPrep security issue?

No. Too complicated.

> Or is there a way to create a private issue?

Not directly from an outsider like me.
I think this can be done by enabling the "Private vulnerability reporting " for the project. Then we could use this for conifidential talks...
See https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability

**Comment by yuki-kimoto** [comment]
https://github.com/yuki-kimoto/gitprep/security/advisories

Is this OK?

**Comment by monnerat** [comment]
> Is this OK?

No. I think you did not really enable it: you have to click on "Enable" on the "Code security and analysis" page.
BTW: we should have a "private issue" flag in gitprep, with a one-time "disclose" button on the issue page.

**Pull request merged**
