### PR TITLE
Merge remotes

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,

This mainly deals with merge strategy and diff computations.
The temporary branch of the working repository is now only used for the merge itself and all branch references are done via remotes elsewhere.
I've also fixed the diff results for PR's. See commit comment.

Regards,
Patrick

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Is it OK? It looks like $parent is not used.

```
            % for my $parent (@$parents) {
              <%= $sep %><a href="<%= url_for("$user_project_path/commit/$parents->[0]") %>">
                <%= substr($parents->[0], 0, 7) %>
              </a>
              % $sep = ' + ';
            % }
```

https://github.com/yuki-kimoto/gitprep/pull/223/commits/54d3c0deeca3113846b9c70c3b7d635256aa2390#diff-79f94e8d8378f5e6ea5194254124c92e667a33bafaaf5d2086164602972af6cbR138

**Comment by yuki-kimoto** [comment]
Honestly spealing, I did not understand the system of pull request in Github, but I wrote source code for pull request in GitPrep. It is likely that there are many bugs. 

I appreciate you fixing the source codes for pull request.

**Comment by monnerat** [comment]
> Is it OK? It looks like $parent is not used.

Ouch! incomplete update. Thanks for review.
Fixed now.

**Comment by monnerat** [comment]
> Honestly speaking, I did not understand the system of pull request in Github, but I wrote source code for pull request in GitPrep. It is likely that there are many bugs.

I thought you were a git guru!
You did it quite well, I can tell you. But the problem is not simple. Github source code is not public, but gitlab is so we could use it as a reference (wriiten in ruby, I'm afraid!).
And yes, there are still many bugs, even some that may appear when someone force pushes a branch involved in a PR with commits erased past the merge base :-(
I don't pretend the remote-based strategy introduced here is the best, but it surely will improve the current merge handling. Merge base is also important and I hope I've grabed it correctly.

> I appreciate you fixing the source codes for pull request.

Thanks.

BTW: do you have a gitprep logo or an idea about it? Like the github cat, it could replace the name on the page header and be eventually used elsewhere.

**Comment by yuki-kimoto** [comment]
> BTW: do you have a gitprep logo or an idea about it? Like the github cat, it could replace the name on the page header and be eventually used elsewhere.

I have no idea for now.

If you have any suggestions, please let me know.

**Comment by monnerat** [comment]
Thanks for merge!
And your opinion about a logo ?

**Comment by yuki-kimoto** [comment]
It would be better to have a logo.

I have no ability to create a logo, but I could use AI to generate logos.

**Comment by monnerat** [comment]
I think it should be simple enough, monochrome, transparent background and not clipped by a `border-radius:50%` to be eventually used as an icon or an avatar.

I'm not a good image designer either, but at this stage, it should be decided if you prefer some figurative (like the cat) or abstract/semi-alpha like the gravatar icon before starting with a pencil !

**Comment by monnerat** [comment]
I just try to combine the g and the p of GitPrep into a logo for brainstorming: it look like an elephant !

gplogo1

**Comment by yuki-kimoto** [comment]
Sorry. I have no artistic sense at all, so I can't come up with anything.

I need a little more your suggestions.

**Comment by monnerat** [comment]
Another one:
gplogo2

**Comment by monnerat** [comment]
To carry on with the elephant idea:
gplogo3
Maybe you prefer another animal/subject.
Tell me your preferences and direction in which I  have to continue, please !

**Comment by yuki-kimoto** [comment]
I'm seeing tree examples.

I want some variations based on the first idea.

https://github.com/yuki-kimoto/gitprep/pull/223#issuecomment-2362501320

**Comment by monnerat** [comment]
> I want some variations based on the first idea.

gplogo4

And its inversed version
gplogo5

**Comment by yuki-kimoto** [comment]
> And its inverted version

OK, and feel free to try and improve it so that g and p are easy to see and the theme is an elephant.

I'm ready to accept it.

**Comment by monnerat** [comment]
Here is another one emphasing the elephant look.
It's hard to improve both p/g look and elephant one as they go the opposite way.

gplogo6

It has lost a tusk, probably during a fight against another elephant ... :-)

**Comment by yuki-kimoto** [comment]
If you are OK with this, let's go ahead.

**Pull request merged**
