### PR TITLE
Replace default Mojolicious exception pages by gitprep-specific ones

### PR DESCRIPTION
**Pull request by monnerat**
I'm submitting this commit as a separate PR as it is more artistic than technical.

It replaces the ugly dinosaur pages by a smart elephant lost in the savanna, in the style of github error pages.
I hope you'll like it !

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
OK. 

This image is a good match for GitPrep icon.

**Comment by monnerat** [comment]
> This image is a good match for GitPrep icon.

Rasterized and just a bit reworked for eyes, ears and the tusk color :-))
The cartoon-like savanna is a real photo processed with gimp filters.

Thanks for merges.

**Comment by yuki-kimoto** [comment]
By the way, could I add you to colloborators?

**Comment by monnerat** [comment]
> By the way, could I add you to colloborators?

Yes, sure.Many thanks for trusting me.
In all cases, I'll continue to submit PRs for review and comments before committing.

**Comment by yuki-kimoto** [comment]
I added you to colloborators now.

**Comment by monnerat** [comment]
> I added you to colloborators now.

Many thanks. I just accepted the invitation!

**Pull request merged**
