### PR TITLE
Reduce git push time by speeding up git hooks start

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,

This commit is a tentative to speed-up git remote operations, at the cost of a slightly less readable code.
See commit comment for more info.

I think we could save another 0.5 seconds if we can RPC the server itself, but needed Mojo features are out of my skill. In addition, it will require the gitprep server to run for git remote operations to be successful.

Cheers,
Patrick

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
My personal preference is to do another optimization first.

This is because the codes of pull request are less readable and use socket programming.

But that's ok if you want(Please wait merge the pull request. I want to review again before merge).

The first optimizations I can think of are:

- Don't `use Gitprep`. This loads whole web application. So it causes slow compliation performance. Separate modules into web application and utility modules, and only load the utility modules.
- use `require` instead of `use` only for modules that significantly slow down compilation time.

**Comment by monnerat** [comment]
> This is because the codes of pull request are less readable

I mentioned this, although I don't see a more readable way of doing it.

> ...  and use socket programming.

Yes. use of an orphan Unix socket is the key to security of this function.

My first idea was to implement the RPC server in the web server itself. Using HTTP for requests/replies.
However for the sake of security, it should not be reachable from an IP socket as it is a privileged API that is not really logged in (access from a foreign program must be forbidden). I planned to use a named Unix socket protected by file permissions as the Mojo server supports it.

The pronlem is the client: I investigated Mojo::UserAgent and unfortunately, it does not support connecting a Unix socket, so another HTTP client should be used (see https://github.com/mojolicious/mojo/pull/1053).

An additional limitation that would be introduced by an RPC server in the gitprep server itself is that git access would not be possible anymore when the server is down.

The solution implemented here is simple and secure and implements 2/3 of what can be done about loading the app at git time: the gitprep shell still needs loading it. We're almost back to the latency we had prior to hooks introduction.

> Don't use Gitprep. This loads whole web application. So it causes slow compliation performance. Separate modules into web application and utility modules, and only load the utility modules.

This PR gets rid of `use Gitprep` in the hooks. Even `require` is not needed. Loading separate modules as you suggest requires Mojo skills that I do not have. In fact, I just mimicked `gitprep-shell-raw` when initially coding the hooks.

> But that's ok if you want(Please wait merge the pull request. I want to review again before merge).

No problem to delay or even drop it if you don't like or have a better solution.
And your review is much valuable to me: I hope the big commit comment will help you in this task.

Thanks for your attention

**Comment by yuki-kimoto** [comment]
Please wait for my optimization of compilation time for a while.

**Comment by monnerat** [comment]
> Please wait for my optimization of compilation time for a while.

Take your time: I'm not in a hurry :-)

**Comment by yuki-kimoto** [comment]
And I have a quetion.

Why not write pre/post logic directly before and after a git command in gitprep-shell-raw?

Are there any features that can only be achieved using Git's hooks/pre-receive and hooks/post-receive?

**Comment by monnerat** [comment]
> Are there any features that can only be achieved using Git's hooks/pre-receive and hooks/post-receive?

Yes.
- Fiirst, the gitprep-shell does not know what kind of transaction is being performed and git decides later if a hook should be called or not.
- Next, I/O channels are not compatible: stdin/stdout are piped differently and their purpose is different.
- Finally, hooks receive transactions info via stdin.

The only way I can imagine to do such a thing would be to move the hook code to the gitprep shell, but still involves a kind of IO channel  to communicate with.

**Comment by yuki-kimoto** [comment]
I understand why hooks are necessary.

**Comment by yuki-kimoto** [comment]
I wrote the following codes to improve compilation performance.

https://github.com/yuki-kimoto/gitprep/tree/compile

Please try it.

And if more perfomanrce is needed, you can proceed to RPC implementation.

**Comment by monnerat** [comment]
> I wrote the following codes to improve compilation performance.

Thanks for this.
I checked with the same test cases and here are my approximate results:

- Current master: 2.5 seconds.
- Compile branch: 2.0 seconds.
- RPC: 1.5 seconds.
- Compile + RPC: 1.4 seconds.

These measurements are consistent: in the first 2 cases, there are 3 loadings, thus we can evalute the compile gain to ~0.16 seconds per load. RPC performs a single load so the improvement by combining with the compile branch is not important.

Are there other optimizations that can be done, like splitting the current app into a web app + a standalone app ? The gain should be big if we can drop most of the framework.

For the RPC PR, you decide. I prefer to reject it rather than introduce code that does not fit your strategy.

**Comment by yuki-kimoto** [comment]
> Are there other optimizations that can be done?

I will try this optimization soon. Please wait for a while.

Could you test it? I cannot do tests for post/pre scripts well.

**Comment by yuki-kimoto** [comment]
Unfortunately, Loading a config file depends on  Mojolicious. It is impossible to sepearte web parts and utilities.

**Comment by yuki-kimoto** [comment]
Considering the possibility that the number of modules that will be loaded may increase in the future, implementing RPC seems like the best option.

**Comment by yuki-kimoto** [comment]
I have a question.

```
my  $channel_fileno = 99;
```

Is 99 never used?

**Comment by monnerat** [comment]
> Unfortunately, loading a config file depends on Mojolicious. It is impossible to sepearte web parts and utilities.

Really bad! In fact, I already tried to understand this part because I wanted to pass addtional parameters from the command line to the app and I did not succeed --> I resigned.

> Considering the possibility that the number of modules that will be loaded may increase in the future, implementing RPC seems like the best option.

Then if you don't object, I'll merge. Maybe your optimizations are worth too.

> Is 99 never used before?

As almost all the file descriptor allocations are dynamic, you'll have to keep 97 files concurrently open to reach this number (0, 1, 2 are stdin, stdout, stderr). I don't believe ssh will open so many files before calling the gitprep shell! And once a descriptor is open, it is not available for dynamic number allocation.
IMHO, this is a reasonable number: not too low for major cases and not too high to stay within a normally-configured system limit.
And there is no chance the git shell closes it explicitly before calling the hooks.

> Could you test it? I cannot do tests for post/pre scripts well.

Yes, sure. If you have something you want me to test, just let a note like https://github.com/yuki-kimoto/gitprep/pull/235#issuecomment-2504961747 and I'll do it.

**Comment by yuki-kimoto** [comment]
> I already tried to understand this part because I wanted to pass addtional parameters from the command line to the app.

This  is simple. `$app->config->{foo}{bar} = 'something'`;

**Comment by yuki-kimoto** [comment]
>Then if you don't object, I'll merge.

Please merge.

**Comment by monnerat** [comment]
> This is simple. $app->config->{foo}{bar} = 'something';

Thanks, but that was not usable: I wanted to pass the config file path !!!

**Comment by monnerat** [comment]
> Please merge.

Done.
Thanks for your review.

**Pull request closed without merging**
