### PR TITLE
Some more

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,
This time we have:
- some github issue fixes,
- work on the wiki

Kind regards,

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
33208da

Can you tell me the reason for the change? 

The local keyword is not recommended in Perl, except for special uses.

**Comment by yuki-kimoto** [comment]
8d7acff

OK.

**Comment by yuki-kimoto** [comment]
d7272c8

OK.

**Comment by monnerat** [comment]
> Can you tell me the reason for the change?

This is to emphasize that the function is constant and not subject to change. In fact, it's a nested subroutiine, not a variable. IMO, this is a special use.
In addition, `subname(`_params_`)` is much more readable than `$var->(`_params_`)`.
If you don't like it, you can drop.

**Comment by yuki-kimoto** [comment]
e8438a6

Almost OK. 

File::Basename is Perl core module.  I think it's better not to add this module to the cpanfile.

**Comment by yuki-kimoto** [comment]
53306a5

OK.

**Comment by monnerat** [comment]
> File::Basename is Perl core module. I think it's better not to add this module to the cpanfile.

I've put this because the Fedora distribution installs it in a separate package, so it does not look like being part of the core.
But you know Perl better than I do and 'll remove it.

**Comment by yuki-kimoto** [comment]
> This is to emphasize that the function is constant and not subject to change. In fact, it's a nested subroutiine, not a variable. IMO, this is a special use.
> In addition, subname(params) is much more readable than $var->(params).
> If you don't like it, you can drop.

OK. I can accept this code like a lexcal sub. 

```
my cb { }
```

**Comment by yuki-kimoto** [comment]
> I've put this because the Fedora distribution installs it in a separate package, so it does not look like being part of the core.
But you know Perl better than I do and 'll remove it.

Please remove the version specific.

```
requires 'File::Basename';
```

**Comment by monnerat** [comment]
> Please remove only the version specific. Do you think this is okay?

I think I will remove this requirement completely. I just checked again and I see Fedora builds it as a subpackage of perl and installs it within perl as a dependency... I don't know why they do it that way.

**Comment by yuki-kimoto** [comment]
> I think I will remove this requirement completely.

OK.

**Comment by monnerat** [comment]
> OK. I can accept this code like a lexcal sub for old Perls.

This is exactly that. I tried with `my` instead of `local`, but this causes a compile error.

**Comment by monnerat** [comment]
> I think I will remove this requirement completely.

Done.

**Comment by monnerat** [comment]
Thanks for merge :-)

**Pull request merged**
