### PR TITLE
Work on labels

### PR DESCRIPTION
**Pull request by monnerat**
- Introduces a unique function to generate label HTML.
- Features a tooltip description.
- Label text black or white depending on the label color luminance.
- Color input uses the browser color picker if available.
- Color indicator replaced by a color input field outline.
- Placeholders in text input fields.
- Check for spoofed label id upon update and delete.

Need to re-run `setup_database` (new db field).

Thanks for your comments.

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
It looks like "description" is not added.

https://github.com/yuki-kimoto/gitprep/blob/8b07db1fbeb7ee1c220351a956963f81d7b34156/setup_database#L284

**Comment by yuki-kimoto** [comment]
image

**Comment by monnerat** [comment]
> Should this font color be white ?

Background is RGB 252, 41, 41.
Converted to HSL is 0/360, 97%, 57%
Luminance is then 57%. I've set the fence to 52% (this is subjective but I think it's better than 50%. Can be easily changed) so the background is on the light side of the fence --> use black as foregrund color.
If you have a better algorithm, I can try it.
In all cases, the most important is it stays readable, whatever the label color is.

**Comment by monnerat** [comment]
> It looks like "description" is not added.

Added, but not checked :-/

Fixed now.

**Comment by yuki-kimoto** [comment]
> Luminance is then 57%. I've set the fence to 52%

OK. For now, let's go with this.

**Comment by monnerat** [comment]
Thanks for merge !

**Pull request merged**
