### PR TITLE
Use a recent screenshot in README

### PR DESCRIPTION
**Pull request by monnerat**
Hi Yuki,

This replaces the screenshot. I think it looks like you have produced it, but please check and report if you want me to change anything.

I also fixed some broken/outdated links in README.md (i.e.: twitter => x). The only ones that should still be reworked are:

- gitprep web site (unreachable),
- google groups forum (no valuable info is displayed).

Maybe you should think of a replacement/removal for those.

Regards,
Patrick

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Thanks.

> I also fixed some broken/outdated links in README.md (i.e.: twitter => x). The only ones that should still be reworked are:
> 
> * gitprep web site (unreachable),
> * google groups forum (no valuable info is displayed).
> 
> Maybe you should think of a replacement/removal for those.

You can remove them.

**Comment by monnerat** [comment]
> Do we assume the github issues can be used can be used for questions too ?

**Comment by monnerat** [comment]
> You can remove them.

Done in this PR.
I've simplified the comment about github issues by suppressing the "for bugs only" clause.

**Comment by monnerat** [comment]
Merged in  master: https://github.com/yuki-kimoto/gitprep/commit/0f6e890556aa2b3cf21f921e4f65d5ef87bda824

**Pull request closed without merging**
