### PR TITLE
Run GitPrep server via sparrow plugin

### PR DESCRIPTION
**Pull request by melezhik**
Hi @yuki-kimoto  this is small documentation update to inform users about possible installation of GitPrep via sparrow plugin.

Regards.

Alexey

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
melezhik

Thanks for your comment.

I hear sparrow tool for the first time.
Please tell me what is sparrow.

**Comment by melezhik** [comment]
Sparrow is a multipurpose scenarios tool. Think about it as of configuration management tool ( sparrow could be thought as a such ). There is [SparrowHub](https://sparrowhub.org) - is a repository of reusable scenarios ( sparrow plugins ). Each plugin to solve a specific task. Users benefit from sparrow in automation some routine tasks. Like installing gitprep implies many other little steps - create a user account, download tarball, inpack it, install dependencies , so on.

Sparrow client needs to get installed to install, run sparrow plugins. Sparrow client itself is cpan module. But sparrow plugins are written on one of three languages to choice - Perl, Ruby or Bash.

A detailed information is on [sparrow github](https://github.com/melezhik/sparrow) pages.

**Comment by yuki-kimoto** [comment]
melezhik

I can introduce sparrow, but a little things is needed.

sparrow is not yet generall way.
so I can introduce sparrow at FAQ section "Are there ohter ways to install GitPrep?"

and I need one page which is linked from FAQ section of GitPrep document.
The page is the complete document to install sparrow and use GitPrep via sparraw.

For example

    cpanm sparraw
    
    # How to use GitPrep via sparraw
    ...
    ...
    ...
    
    sparrow plg run gitprep --param action=install   # to install GitPrep server
    sparrow plg run gitprep --param action=start     # to start GitPrep server
    sparrow plg run gitprep --param action=stop      # to stop GitPrep server

OK?

**Comment by melezhik** [comment]
Hi!

> sparrow is not yet generall way. so I can introduce sparrow at FAQ section "Are there ohter ways to install GitPrep?"

Sure! Sparrow is kinda alternative approach for people who don't want to hack into manual approach, that is fine.

> and I need one page which is linked from FAQ section of GitPrep document.

Let me complete my pull request, I will add want you want ... soon

**Comment by melezhik** [comment]
> and I need one page which is linked from FAQ section of GitPrep document.

Basically you may link to getprep sparrow plugin page directly -  https://sparrowhub.org/info/gitprep where all the information is at. 

Or you need some summary at gitprep doc as well?

**Comment by melezhik** [comment]
Hi I have update https://github.com/melezhik/gitprep-install with more detailed explanation of usage sparrow to install GitPrep server

**Comment by yuki-kimoto** [comment]
melezhik

OK. That page seems pretty good.

Please fix your pull request by move sparrow description to FAQ section and link to that page.

**Comment by melezhik** [comment]
Hi @yuki-kimoto!  I have updated pull request, please take a look.

**Comment by yuki-kimoto** [comment]
melezhik 

Good. I will merge it and add a little fix.

**Comment by melezhik** [comment]
Thanks a lot! :smile:

**Pull request merged**
