### PR TITLE
swat integrartion tests for gitgrep

### PR DESCRIPTION
**Pull request by melezhik**
HI Yuki! 

I noticed no integration tests for gitprep application (t/ holds only few unit tests ). So I have droped a few smoke tests could be used as regression integration tests for gitrep, please follow [README.md](https://github.com/melezhik/gitprep/blob/master/swat/README.md) inside swat/ directory for details.

Regards.

Alexey

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
GitPrep test depend on Repository content. t directory is for user. I use xt/ directory for GitPrep tests.

**Comment by melezhik** [comment]
Hi Yuki!

Ahh, did not notice xt/ directory tests, now I see this is for integration part tests ... Ok, that is good :smile: 

Don't you consider a third party integration tests though? The conception is  described here -  http://blogs.perl.org/users/melezhik/2016/02/3part---cpan-modules-third-party-testing.html 

Let me know if this of interest for you ... Thanks 

Alexey

**Comment by yuki-kimoto** [comment]
I see swat project. But I want to write all tests by perl script. Sorry.

**Comment by melezhik** [comment]
Ok, then wish you all the best!

2016-02-26 12:05 GMT+03:00 Yuki Kimoto <notifications@github.com>:

**Pull request closed without merging**
