### PR TITLE
Install gitprep by sparrowdo

### PR DESCRIPTION
**Pull request by melezhik**
Hi @yuki-kimoto ! here is sparrowdo installer for git prep. It might be useful for cross-platform installs for both ssh/docker flavours.
For example for docker one can run:

```
$ docker pull bitnami/minideb-extras # minimal debian image
$ docker run  --expose 10020:10020  --name instance0 -it -d  bitnami/minideb-extras bash
$  sparrowdo --docker=instance1 --no_sudo --sparrowfile=sparrowfile.install.pl6  --format=production
$ firefox  127.0.0.1:10020
```
I have tested it for alpine and debian, probably other OS should work smoothly ...

### CODE REVIEW

**Comment by yuki-kimoto** [comment]
Can you change file path to deploy/sparrowfile.install.pl6?

And Can you add some document to FAQ section?

**Comment by melezhik** [comment]
Hi @yuki-kimoto 
I've updated my merge request. Please let me know if it's ok.

**Comment by yuki-kimoto** [comment]
It seems to be good. I merge this pull request. Thanks for your contribute.

**Comment by melezhik** [comment]
Good! Let me know if you have any issues with this.
Thanks.

**Pull request merged**
